package test1

type Data struct {
	Column1   float64 `parquet:"name=Column1,type=DOUBLE"`
	Column2   string  `parquet:"name=Column2,type=BYTE_ARRAY"`
	Column3   float64 `parquet:"name=Column3,type=DOUBLE"`
	Column4   float64 `parquet:"name=Column4,type=DOUBLE"`
	Column5   float64 `parquet:"name=Column5,type=DOUBLE"`
	Column6   string  `parquet:"name=Column6,type=BYTE_ARRAY"`
	Column7   float64 `parquet:"name=Column7,type=DOUBLE"`
	Column8   float64 `parquet:"name=Column8,type=DOUBLE"`
	Column9   float64 `parquet:"name=Column9,type=DOUBLE"`
	Column10  string  `parquet:"name=Column10,type=BYTE_ARRAY"`
	Column11  float64 `parquet:"name=Column11,type=DOUBLE"`
	Column12  float64 `parquet:"name=Column12,type=DOUBLE"`
	Column13  float64 `parquet:"name=Column13,type=DOUBLE"`
	Column14  string  `parquet:"name=Column14,type=BYTE_ARRAY"`
	Column15  float64 `parquet:"name=Column15,type=DOUBLE"`
	Column16  float64 `parquet:"name=Column16,type=DOUBLE"`
	Column17  float64 `parquet:"name=Column17,type=DOUBLE"`
	Column18  string  `parquet:"name=Column18,type=BYTE_ARRAY"`
	Column19  float64 `parquet:"name=Column19,type=DOUBLE"`
	Column20  float64 `parquet:"name=Column20,type=DOUBLE"`
	Column21  float64 `parquet:"name=Column21,type=DOUBLE"`
	Column22  string  `parquet:"name=Column22,type=BYTE_ARRAY"`
	Column23  float64 `parquet:"name=Column23,type=DOUBLE"`
	Column24  float64 `parquet:"name=Column24,type=DOUBLE"`
	Column25  float64 `parquet:"name=Column25,type=DOUBLE"`
	Column26  string  `parquet:"name=Column26,type=BYTE_ARRAY"`
	Column27  float64 `parquet:"name=Column27,type=DOUBLE"`
	Column28  float64 `parquet:"name=Column28,type=DOUBLE"`
	Column29  float64 `parquet:"name=Column29,type=DOUBLE"`
	Column30  string  `parquet:"name=Column30,type=BYTE_ARRAY"`
	Column31  float64 `parquet:"name=Column31,type=DOUBLE"`
	Column32  float64 `parquet:"name=Column32,type=DOUBLE"`
	Column33  float64 `parquet:"name=Column33,type=DOUBLE"`
	Column34  string  `parquet:"name=Column34,type=BYTE_ARRAY"`
	Column35  float64 `parquet:"name=Column35,type=DOUBLE"`
	Column36  float64 `parquet:"name=Column36,type=DOUBLE"`
	Column37  float64 `parquet:"name=Column37,type=DOUBLE"`
	Column38  string  `parquet:"name=Column38,type=BYTE_ARRAY"`
	Column39  float64 `parquet:"name=Column39,type=DOUBLE"`
	Column40  float64 `parquet:"name=Column40,type=DOUBLE"`
	Column41  float64 `parquet:"name=Column41,type=DOUBLE"`
	Column42  string  `parquet:"name=Column42,type=BYTE_ARRAY"`
	Column43  float64 `parquet:"name=Column43,type=DOUBLE"`
	Column44  float64 `parquet:"name=Column44,type=DOUBLE"`
	Column45  float64 `parquet:"name=Column45,type=DOUBLE"`
	Column46  string  `parquet:"name=Column46,type=BYTE_ARRAY"`
	Column47  float64 `parquet:"name=Column47,type=DOUBLE"`
	Column48  float64 `parquet:"name=Column48,type=DOUBLE"`
	Column49  float64 `parquet:"name=Column49,type=DOUBLE"`
	Column50  string  `parquet:"name=Column50,type=BYTE_ARRAY"`
	Column51  float64 `parquet:"name=Column51,type=DOUBLE"`
	Column52  float64 `parquet:"name=Column52,type=DOUBLE"`
	Column53  float64 `parquet:"name=Column53,type=DOUBLE"`
	Column54  string  `parquet:"name=Column54,type=BYTE_ARRAY"`
	Column55  float64 `parquet:"name=Column55,type=DOUBLE"`
	Column56  float64 `parquet:"name=Column56,type=DOUBLE"`
	Column57  float64 `parquet:"name=Column57,type=DOUBLE"`
	Column58  string  `parquet:"name=Column58,type=BYTE_ARRAY"`
	Column59  float64 `parquet:"name=Column59,type=DOUBLE"`
	Column60  float64 `parquet:"name=Column60,type=DOUBLE"`
	Column61  float64 `parquet:"name=Column61,type=DOUBLE"`
	Column62  string  `parquet:"name=Column62,type=BYTE_ARRAY"`
	Column63  float64 `parquet:"name=Column63,type=DOUBLE"`
	Column64  float64 `parquet:"name=Column64,type=DOUBLE"`
	Column65  float64 `parquet:"name=Column65,type=DOUBLE"`
	Column66  string  `parquet:"name=Column66,type=BYTE_ARRAY"`
	Column67  float64 `parquet:"name=Column67,type=DOUBLE"`
	Column68  float64 `parquet:"name=Column68,type=DOUBLE"`
	Column69  float64 `parquet:"name=Column69,type=DOUBLE"`
	Column70  string  `parquet:"name=Column70,type=BYTE_ARRAY"`
	Column71  float64 `parquet:"name=Column71,type=DOUBLE"`
	Column72  float64 `parquet:"name=Column72,type=DOUBLE"`
	Column73  float64 `parquet:"name=Column73,type=DOUBLE"`
	Column74  string  `parquet:"name=Column74,type=BYTE_ARRAY"`
	Column75  float64 `parquet:"name=Column75,type=DOUBLE"`
	Column76  float64 `parquet:"name=Column76,type=DOUBLE"`
	Column77  float64 `parquet:"name=Column77,type=DOUBLE"`
	Column78  string  `parquet:"name=Column78,type=BYTE_ARRAY"`
	Column79  float64 `parquet:"name=Column79,type=DOUBLE"`
	Column80  float64 `parquet:"name=Column80,type=DOUBLE"`
	Column81  float64 `parquet:"name=Column81,type=DOUBLE"`
	Column82  string  `parquet:"name=Column82,type=BYTE_ARRAY"`
	Column83  float64 `parquet:"name=Column83,type=DOUBLE"`
	Column84  float64 `parquet:"name=Column84,type=DOUBLE"`
	Column85  float64 `parquet:"name=Column85,type=DOUBLE"`
	Column86  string  `parquet:"name=Column86,type=BYTE_ARRAY"`
	Column87  float64 `parquet:"name=Column87,type=DOUBLE"`
	Column88  float64 `parquet:"name=Column88,type=DOUBLE"`
	Column89  float64 `parquet:"name=Column89,type=DOUBLE"`
	Column90  string  `parquet:"name=Column90,type=BYTE_ARRAY"`
	Column91  float64 `parquet:"name=Column91,type=DOUBLE"`
	Column92  float64 `parquet:"name=Column92,type=DOUBLE"`
	Column93  float64 `parquet:"name=Column93,type=DOUBLE"`
	Column94  string  `parquet:"name=Column94,type=BYTE_ARRAY"`
	Column95  float64 `parquet:"name=Column95,type=DOUBLE"`
	Column96  float64 `parquet:"name=Column96,type=DOUBLE"`
	Column97  float64 `parquet:"name=Column97,type=DOUBLE"`
	Column98  string  `parquet:"name=Column98,type=BYTE_ARRAY"`
	Column99  float64 `parquet:"name=Column99,type=DOUBLE"`
	Column100 float64 `parquet:"name=Column100,type=DOUBLE"`
}
